export const Movies = [
    {
        id: 1,
    Title: 'A Mothers Lie', 
    Epilogue: 'A woman\'s hidden past comes to light, threatening her family\'s future.',
    DateReleased: '2024',
    Category: 'Drama',
    Type: 'Feature Film',
    Actors: ['Nse Ikpe-Etim', 'Ramsey Nouah', 'Kate Henshaw'],
    Keywords: ['Family', 'Secrets', 'Drama'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 2,
    Title: "Twice the Love",
    Epilogue: 'Twin sisters navigate love and life, facing unexpected challenges.',
    DateReleased: ['2024.'],
    Category: 'Romance, Drama',
    Type: ['FeatureFilm'],
    Actors: ['Adesua Etomi, Beverly Naya, Kunle Remi'],
    Keywords: ['Twins, Love, Drama'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 3,
    Title: 'A Tribe Called Judah',
    Epilogue: 'A young man discovers his royal heritage and must fight to reclaim his throne.',
    DateReleased: '2023',
    Category: 'Action, Drama.',
    Type: 'Feature Film',
    Actors: ['Alexx Ekubo, Ini Edo, Desmond Elliot'],
    Keywords: ['Royalty, Heritage, Action'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id:4,
    Title: 'The Black Book',
    Epilogue: 'A detective uncovers a conspiracy that leads to a powerful secret society.',
    DateReleased: '2023',
    Category: 'Thriller, Mystery',
    Type: 'Feature Film',
    Actors: ['Richard Mofe-Damijo, Rita Dominic, OC Ukeje'],
    Keywords: ['Conspiracy, Detective, Thriller'],
    Kind: 'R',
    Rating: '5'
    },
    
    {
        id: 5,
    Title: 'Breath of Life',
    Epilogue: 'A doctor’s life changes when she meets a mysterious patient with a miraculous story.',
    DateReleased: '2023',
    Category: 'Drama, Fantasy',
    Type: 'Feature Film',
    Actors: ['Genevieve Nnaji, Deyemi Okanlawon, Bimbo Akintola'],
    Keywords: ['Miracle, Doctor, Fantasy'],
    Kind: 'PG',
    Rating: '5',
    },
    
    {
        id: 6,
    Title: 'Funmilayo Ransome Kuti',
    Epilogue: ['The inspiring story of Nigeria’s foremost female activist and her fight for women’s rights.'],
    DateReleased: '2024',
    Category: 'Biography, Drama',
    Type: 'Feature Film',
    Actors: ['Joke Silva, Taiwo Ajai-Lycett, Sola Sobowale'],
    Keywords: ['Activism, Biography, Women’s Rights'],
    Kind: 'PG',
    Rating: '5',
    },
    
    {
        id: 7,
    Title: 'The bridge',
    Epilogue: 'A mute girl witnesses a crime and must find a way to communicate the truth.',
    DateReleased: '2024',
    Category: 'Thriller, Drama',
    Type: 'Feature Film',
    Actors: ['Chidinma Ekile, Blossom Chukwujekwu, Uche Jombo'],
    Keywords: ['Crime, Mute, Thriller'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 8,
    Title: 'Dwindle',
    Epilogue: 'Four friends navigate the ups and downs of life in Lagos.',
    DateReleased: '2024',
    Category: 'Drama, Comedy',
    Type: 'Feature Film',
    Actors: ['Falz, Bisola Aiyeola, Timini Egbuson'],
    Keywords: ['Friendship, Lagos, Comedy'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 9,
    Title: 'A Weekend to Forget',
    Epilogue: 'A group of friends’ weekend getaway turns into a nightmare.',
    DateReleased: '2023',
    Category: 'Horror, Thriller',
    Type: 'Feature Film',
    Actors: ['Zainab Balogun, Mawuli Gavor, Nancy Isime'],
    Keywords: ['Getaway, Horror, Thriller'],
    Kind: 'R',
    Rating: '5',
    },
    
    {
        id: 10,
    Title: 'Coming from Insanity',
    Epilogue: 'A young man’s journey to self-discovery and acceptance.',
    DateReleased: '2024',
    Category: 'Drama',
    Type: 'Feature Film',
    Actors: ['Tope Tedela, Bimbo Ademoye, Wale Ojo'],
    Keywords: ['Self-discovery, Acceptance, Drama'],
    Kind: 'PG',
    Rating: '5',
    },
    
    {
        id: 11,
    Title: 'The Arbitration',
    Epilogue: 'A deadly kiss sets off a chain of events that changes lives forever.',
    DateReleased: '2024',
    Category: 'Thriller, Romance',
    Type: 'Feature Film',
    Actors: ['Nse Ikpe-Etim, OC Ukeje, Beverly Naya'],
    Keywords: ['Kiss, Thriller, Romance'],
    Kind: 'R',
    Rating: '5',
    },
    
    {
        id: 12,
    Title: 'Private Storm',
    Epilogue: 'A family’s peaceful life is disrupted by a mysterious intruder.',
    DateReleased: '2024',
    Category: 'Thriller, Mystery',
    Type: 'Feature Film',
    Actors: ['Ramsey Nouah, Kate Henshaw, Blossom Chukwujekwu'],
    Keywords: ['Intruder, Mystery, Thriller'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 13,
    Title: 'A Song from the Dark',
    Epilogue: 'A haunted musician must confront his past to find peace.',
    DateReleased: '2024',
    Category: 'Horror, Drama',
    Type: 'Feature Film',
    Actors: ['OC Ukeje, Adesua Etomi, Sola Sobowale'],
    Keywords: ['Haunted, Musician, Horror'],
    Kind: 'R',
    Rating: '5',
    },
    
    {
        id: 14,
    Title: 'As We Are',
    Epilogue: 'A couple’s relationship is tested by unexpected challenges.',
    DateReleased: '2023',
    Category: 'Drama, Romance',
    Type: 'Feature Film',
    Actors: ['Adesua Etomi, Kunle Remi, Beverly Naya'],
    Keywords: ['Relationship, Challenges, Romance'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 15,
    Title: 'Merry Men 3',
    Epilogue: 'The Merry Men face their toughest challenge yet as they confront a powerful enemy.',
    DateReleased: '2023',
    Category: 'Action, Comedy',
    Type: 'Feature Film',
    Actors: ['AY Makun, Ramsey Nouah, Jim Iyke'],
    Keywords: ['Action, Comedy, Heist'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 16,
    Title: 'When You Are Mine',
    Epilogue: 'A love story complicated by secrets and betrayal.',
    DateReleased: '2023',
    Category: 'Romance, Drama',
    Type: 'Feature Film',
    Actors: ['Adesua Etomi, Kunle Remi, Beverly Naya'],
    Keywords: ['Love, Secrets, Betrayal'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 17,
    Title: 'Downright Fondness',
    Epilogue: 'Two people from different worlds find love against all odds.',
    DateReleased: '2024',
    Category: 'Romance, Drama',
    Type: 'Feature Film',
    Actors: ['Nse Ikpe-Etim, OC Ukeje, Beverly Naya'],
    Keywords: ['Love, Different Worlds, Drama'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 18,
    Title: 'Afamefuna',
    Epilogue: 'A young man’s quest to honor his family’s legacy.',
    DateReleased: '2023',
    Category: 'Drama',
    Type: 'Feature Film',
    Actors: ['Alexx Ekubo, Ini Edo, Desmond Elliot'],
    Keywords: ['Legacy, Family, Drama'],
    Kind: 'PG',
    Rating: '5',
    },
    
    {
        id: 19,
    Title: 'Breaking Point',
    Epilogue: 'A woman’s struggle to balance her career and personal life.',
    DateReleased: '2023',
    Category: 'Drama',
    Type: 'Feature Film',
    Actors: ['Genevieve Nnaji, Deyemi Okanlawon, Bimbo Akintola'],
    Keywords: ['Career, Personal Life, Drama'],
    Kind: 'PG',
    Rating: '5',
    },
    
    {
        id: 20,
    Title: 'It Blooms in june',
    Epilogue: 'A woman finds hope and love in the most unexpected places.',
    DateReleased: '2024',
    Category: 'Drama, Romance',
    Type: 'Feature Film',
    Actors: ['Nse Ikpe-Etim, OC Ukeje, Beverly Naya'],
    Keywords: ['Hope, Love, Drama'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 21,
    Title: 'The set up',
    Epilogue: 'A group of thieves plan one final heist that could change their lives forever.',
    DateReleased: '2023',
    Category: 'Action, Thriller',
    Type: 'Feature Film',
    Actors: ['Ramsey Nouah, Jim Iyke, Adesua Etomi'],
    Keywords: ['Heist, Action, Thriller'],
    Kind: 'R',
    Rating: '5',
    },
    
    {
        id: 22,
    Title: 'king of boys',
    Epilogue: 'A historian uncovers secrets that link her to a forgotten era.',
    DateReleased: '2024',
    Category: 'Mystery, Drama',
    Type: 'Feature Film',
    Actors: ['Genevieve Nnaji, Richard Mofe-Damijo, Bimbo Akintola'],
    Keywords: ['History, Secrets, Mystery'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 23,
    Title: 'The Unseen',
    Epilogue: 'A detective investigates a series of mysterious disappearances in a small town.',
    DateReleased: '2023',
    Category: 'Thriller, Mystery',
    Type: 'Feature Film',
    Actors: ['OC Ukeje, Kate Henshaw, Blossom Chukwujekwu'],
    Keywords: ['Disappearances, Detective, Thriller'],
    Kind: 'R',
    Rating: '5',
    },
    
    {
        id: 24,
    Title: 'living in bondage',
    Epilogue: 'A young man must prove himself worthy of inheriting his family’s empire.',
    DateReleased: '2024',
    Category: 'Drama',
    Type: 'Feature Film',
    Actors: ['Alexx Ekubo, Ini Edo, Desmond Elliot'],
    Keywords: ['Inheritance, Family, Drama'],
    Kind: 'PG',
    Rating: '5',
    },
    
    {
        id: 25,
    Title: 'Brotherhood',
    Epilogue: 'A couple devises a plan to save their failing marriage.',
    DateReleased: '2023',
    Category: 'Romance, Drama',
    Type: 'Feature Film',
    Actors: ['Adesua Etomi, Kunle Remi, Beverly Naya'],
    Keywords: ['Marriage, Plan, Romance'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 26,
    Title: 'Anikulapo',
    Epilogue: 'A journalist uncovers a conspiracy that puts her life in danger.',
    DateReleased: '2024',
    Category: 'Thriller, Drama',
    Type: 'Feature Film',
    Actors: ['Genevieve Nnaji, Deyemi Okanlawon, Bimbo Akintola'],
    Keywords: ['Conspiracy, Journalist, Thriller'],
    Kind: 'R',
    Rating: '5',
    },
    
    {
        id: 27,
    Title: 'blood sisters',
    Epilogue: 'An archaeologist discovers a lost kingdom and must protect it from treasure hunters.',
    DateReleased: '2023',
    Category: 'Adventure, Drama',
    Type: 'Feature Film',
    Actors: ['Richard Mofe-Damijo, Rita Dominic, OC Ukeje'],
    Keywords: ['Archaeology, Kingdom, Adventure'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 28,
    Title: 'ijakumo',
    Epilogue: 'A rising star grapples with the dark side of fame.',
    DateReleased: '2024',
    Category: 'Drama',
    Type: 'Feature Film',
    Actors: ['Nse Ikpe-Etim, OC Ukeje, Beverly Naya'],
    Keywords: ['Fame, Stardom, Drama'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 29,
    Title: 'Jagun Jagun',
    Epilogue: 'A mute girl becomes the key witness in a high-profile murder case.',
    DateReleased: '2024',
    Category: 'Thriller, Drama',
    Type: 'Feature Film',
    Actors: ['Chidinma Ekile, Blossom Chukwujekwu, Uche Jombo'],
    Keywords: ['Witness, Murder, Thriller'],
    Kind: 'PG-13',
    Rating: '5',
    },
    
    {
        id: 30,
    Title: 'Blood Vessel',
    Epilogue: 'A man seeks redemption for his past mistakes.',
    DateReleased: '2023',
    Category: 'Drama',
    Type: 'Feature Film',
    Actors: ['Genevieve Nnaji, Deyemi Okanlawon, Bimbo Akintola'],
    Keywords: ['Redemption, Mistakes, Drama'],
    Kind: 'PG',
    Rating: '5',
    },
    ];
    